EmailValidation/Models/EmailModel.cs
using EmailValidation.Helpers;
using System.ComponentModel.DataAnnotations;

namespace EmailValidation.Models
{
    public class EmailModel
    {
        [Display(Name = "Adresse Email")]
        [Required(ErrorMessage = "Veuillez saisir un email à valider.")]
        [EmailAddress(ErrorMessage = "L'email saisi n'est pas valide.")]
        [CustomEmailLoginValidation()]
        [CustomEmailRegexValidation()]
        [CustomEmailGeolocValidation()]
        public string Email { get; set; }
    }
}

EmailValidation/Models/GeoIpModel.cs
using Newtonsoft.Json;

namespace EmailValidation.Models
{
    public class GeoIpModel
    {
        [JsonProperty("ip")]
        public string Ip { get; set; }
        [JsonProperty("country_code")]
        public string CountryCode { get; set; }
        [JsonProperty("country_name")]
        public string CountryName { get; set; }
        [JsonProperty("region_code")]
        public string RegionCode { get; set; }
        [JsonProperty("region_name")]
        public string RegionName { get; set; }
        [JsonProperty("city")]
        public string City { get; set; }
        [JsonProperty("zip_code")]
        public string ZipCode { get; set; }
        [JsonProperty("time_zone")]
        public string TimeZone { get; set; }
        [JsonProperty("latitude")]
        public double Latitude { get; set; }
        [JsonProperty("longitude")]
        public double Longitude { get; set; }
        [JsonProperty("metro_code")]
        public int MetroCode { get; set; }
    }
}

EmailValidation/Controllers/EmailValidationController.cs
using EmailValidation.Models;
using System.Web.Mvc;

namespace EmailValidation.Controllers
{
    public class EmailValidationController : Controller
    {
        private static readonly log4net.ILog log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        // GET: EmailValidation
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(EmailModel model)
        {
            if (ModelState.IsValid)
            {
                log.Debug(model.Email);
                return View(model);
            }
            return View();
        }
    }
}

EmailValidation/Controllers/HomeController.cs
using System.Web.Mvc;

namespace EmailValidation.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }
    }
}

EmailValidation/Views/EmailValidation/Index.cshtml
@model EmailValidation.Models.EmailModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="row">
    @using (Html.BeginForm("Index", "EmailValidation", FormMethod.Post))
    {

        <div class="form-group">
            @Html.LabelFor(m => m.Email, new { @class = "font-weight-bold" })
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control", @placeholder = "Email" })
            @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger d-block" })
        </div>
        <button type="submit" class="btn btn-primary">Valider</button>

        
    }
</div>
@if (ViewData.ModelState.Count > 0 && ViewData.ModelState.IsValid)
{
    <div class="row mt-3">
        <div class="form-group">
            <p>
                <code>@Model.Email</code> est bien une adresse email valide !
            </p>            
            <img src="~/Content/valid.png" class="emailValid" />
        </div>
    </div>
}

EmailValidation/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>Laurent Signorel</h3>

<address>
    68 Boulevard François GROSSO<br />
    06000 Nice - France<br />
    <abbr title="mobile">tél:</abbr>
    +33.760972790
</address>

<address>
    <a href="mailto:laurent.signorel@outlook.com">laurent.signorel@outlook.com</a><br />
</address>

EmailValidation/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Email Validation App</h1>
    <p class="lead">Application permettant la validation d'un email par critères définis au préalable.</p>
    @Html.ActionLink("Validation", "Index", "EmailValidation", new { area = "" }, new { @class = "btn btn-primary btn-lg" })
    @*<p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>*@
</div>

<div class="row">
    <div class="col-md-6">
        <h2>Vérification syntaxique</h2>
        <ul>
            <li>
                L'email à valider doit correspondre à la syntaxe suivante : <code>identifiant@domaine.extension</code>
            </li>
            <li>
                <code>[identifiant]</code> doit commencer par une lettre et contenir plus de lettres que de chiffres.
            </li>
            <li>
                <code>[domaine]</code> fait référence à un domaine avec un maximum de trois sous domaines.
            </li>
            <li>
                <code>[extension]</code> fait référence à l'extension du domaine (ex : .fr, .de, .mc...).
            </li>
        </ul>
    </div>
    <div class="col-md-6">
        <h2>Limitation aux pays limitrophes</h2>
        <p>
            Le domaine de l'email sera limité aux pays limitrophes de la france grace au service de géolocalisation fourni par <strong>Free IP Geolocation API</strong><br />
            <a class="btn btn-primary" href="https://freegeoip.app/">go to freegeoip</a>
        </p>
    </div>
</div>

EmailValidation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <nav class="navbar navbar-expand-md bg-dark navbar-dark">
        <!-- Brand -->
        @Html.ActionLink("Email Validation", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })

        <!-- Toggler/collapsibe Button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Navbar links -->
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav">
                <li class="nav-item">
                    @Html.ActionLink("Validation", "Index", "EmailValidation", new { area = "" }, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })
                </li>
            </ul>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Laurent Signorel</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>